In [3]:
import pandas as pd
df = pd.read_csv("D:\SIRPI\Automobile.csv")
print(df.head(30))

    symboling  normalized_losses         make fuel_type aspiration  \
0           3                168  alfa-romero       gas        std   
1           3                168  alfa-romero       gas        std   
2           1                168  alfa-romero       gas        std   
3           2                164         audi       gas        std   
4           2                164         audi       gas        std   
5           2                161         audi       gas        std   
6           1                158         audi       gas        std   
7           1                168         audi       gas        std   
8           1                158         audi       gas      turbo   
9           2                192          bmw       gas        std   
10          0                192          bmw       gas        std   
11          0                188          bmw       gas        std   
12          0                188          bmw       gas        std   
13          1       

In [4]:
print(df.columns)

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')


In [5]:
print(df.shape)

(201, 26)


In [6]:
print(df.dtypes)

symboling                int64
normalized_losses        int64
make                    object
fuel_type               object
aspiration              object
number_of_doors         object
body_style              object
drive_wheels            object
engine_location         object
wheel_base             float64
length                 float64
width                  float64
height                 float64
curb_weight              int64
engine_type             object
number_of_cylinders     object
engine_size              int64
fuel_system             object
bore                   float64
stroke                 float64
compression_ratio      float64
horsepower               int64
peak_rpm                 int64
city_mpg                 int64
highway_mpg              int64
price                    int64
dtype: object


In [26]:
min_price = df["price"].min()
max_price = df["price"].max()

min_fuel_type = df[df["price"] == min_price]["fuel_type"].values[0]
max_fuel_type = df[df["price"] == max_price]["fuel_type"].values[0]

print(f"Min Price: {min_price}, Fuel Type: {min_fuel_type}")
print(f"Max Price: {max_price}, Fuel Type: {max_fuel_type}")

Min Price: 5118, Fuel Type: gas
Max Price: 45400, Fuel Type: gas


In [28]:
print(df["engine_type"].unique())

['dohc' 'ohcv' 'ohc' 'l' 'rotor' 'ohcf']


In [29]:
print(f"Horsepower Range: {df['horsepower'].min()} - {df['horsepower'].max()}")

Horsepower Range: 48 - 262


In [34]:
city_avg = df["city_mpg"].mean()
highway_avg = df["highway_mpg"].mean()
better_mpg = "Highway" if highway_avg > city_avg else "City"
print(f"City MPG: {city_avg}, Highway MPG: {highway_avg}. Better: {better_mpg}")

City MPG: 25.17910447761194, Highway MPG: 30.686567164179106. Better: Highway


In [37]:
make_counts = df["make"].value_counts()
print(make_counts)
print(f"Most common make: {make_counts.idxmax()} ({make_counts.max()} cars)")

make
toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
plymouth          7
audi              6
saab              6
porsche           4
jaguar            3
chevrolet         3
alfa-romero       3
isuzu             2
renault           2
mercury           1
Name: count, dtype: int64
Most common make: toyota (32 cars)


In [39]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
print(df.loc[df["Name"] == "Charlie"])



      Name  Age  Score
2  Charlie   22     78


In [40]:
print(df.loc[df["Name"].isin(["Alice", "Bob"]), ["Age", "Score"]])

   Age  Score
0   24     85
1   27     90


In [41]:
print(df.iloc[1])

Name     Bob
Age       27
Score     90
Name: 1, dtype: object


In [42]:
print(df.iloc[-2:])

      Name  Age  Score
2  Charlie   22     78
3    David   32     88


In [43]:
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Bob", "David"],
    "Salary": [50000, 60000, 55000, 65000],
    "Department": ["IT", "HR", "IT", "Finance"]
})

print(df[df["Department"] == "IT"])
print(df[df["Salary"] > 55000])


  Employee  Salary Department
0     John   50000         IT
2      Bob   55000         IT
  Employee  Salary Department
1    Alice   60000         HR
3    David   65000    Finance


In [44]:
df = pd.DataFrame({
    "Student": ["A", "B", "C", "D"],
    "Marks": [45, 78, 62, 90]
})

def pass_fail(mark):
    return "Pass" if mark >= 50 else "Fail"

df["Result"] = df["Marks"].apply(pass_fail)
print(df)


  Student  Marks Result
0       A     45   Fail
1       B     78   Pass
2       C     62   Pass
3       D     90   Pass


In [45]:
import numpy as np

arr = np.arange(1, 13).reshape(3, 4)
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a * b)
print(a + 5)


[10 40 90]
[6 7 8]


In [49]:
arr = np.array([[3, 7, 2], [4, 9, 6]])

print("Max value:", arr.max())
print("Min in each row:", arr.min(axis=1))

Max value: 9
Min in each row: [2 4]


In [50]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})

print(df.groupby("Department")["Salary"].mean())


Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64


In [51]:
df = pd.DataFrame({
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Population": [8419600, 3980400, 2716000, 2328000]
})

print(df.sort_values(by="Population", ascending=False))


          City  Population
0     New York     8419600
1  Los Angeles     3980400
2      Chicago     2716000
3      Houston     2328000


In [52]:
df = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "East", "East"],
    "City": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 150, 180, 220, 300, 250]
}).set_index(["Region", "City"])

print(df.loc[("South", "A"), "Sales"])

180


In [53]:
arr = np.random.randint(10, 99, (5, 4))
df = pd.DataFrame(arr, columns=["A", "B", "C", "D"])
print(df)

    A   B   C   D
0  14  65  55  11
1  41  22  53  14
2  40  53  32  55
3  85  22  62  96
4  73  86  91  43


In [60]:

print(df.columns)

Index(['A', 'B', 'C', 'D'], dtype='object')


In [63]:
df.loc[df["D"] < 60, "Marks"] = 0

In [74]:

df.columns = ["Student", "Attendance", "Marks", "Grade", "d"]

df["Attendance"] = pd.to_numeric(df["Attendance"], errors="coerce")

df.loc[df["Attendance"] < 60, "Marks"] = 0

print(df.head())

   Student  Attendance  Marks  Grade    d
0       14          65     55     11  0.0
1       41          22      0     14  0.0
2       40          53      0     55  0.0
3       85          22      0     96  NaN
4       73          86     91     43  0.0


In [77]:
data = {
    "EmployeeID": [1, 2, 3, 4, 5],
    "Department": ["IT", "Finance", "HR", "IT", "Finance"],
    "Salary": [70000, 80000, 55000, 65000, 75000],
    "Experience": [6, 7, 3, 5, 8]
}

df = pd.DataFrame(data)
df.to_csv("employees.csv", index=False)
df = pd.read_csv('employees.csv')

new_df =  df.query('Department in ["IT", "Finance"] and Salary > 60000 and Experience >= 5')
new_df
     

EmployeeID Department  Salary  Experience
0           1         IT   70000           6
1           2    Finance   80000           7
3           4         IT   65000           5
4           5    Finance   75000           8

In [78]:
df = pd.read_csv("employees.csv")

filtered = df[(df["Department"].isin(["IT", "Finance"])) & (df["Salary"] > 60000) & (df["Experience"] >= 5)]
print(filtered)

   EmployeeID Department  Salary  Experience
0           1         IT   70000           6
1           2    Finance   80000           7
3           4         IT   65000           5
4           5    Finance   75000           8


In [79]:
df.groupby("Department").apply(lambda x: x[x["Experience"] >= 5]["Salary"].mean())

Department
Finance    77500.0
HR             NaN
IT         67500.0
dtype: float64

In [80]:
arr = np.random.randint(1, 101, (5, 5))

print(arr[arr % 2 == 0])  # Extract even numbers
print(arr[-1, :])  # Last row
print(arr[:, -1])  # Last column

arr[arr > 50] = 0
print(arr)


[14 62  6 66 98  6  2  2 56 34 36 18 26 66 90]
[36 18 26 66 90]
[19 79  2 85 90]
[[14  0  0 15 19]
 [ 6  0  0  0  0]
 [ 6  3  0 11  2]
 [ 2  0  0 34  0]
 [36 18 26  0  0]]


In [81]:

data = {
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
    "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
    "Experience": [5, 4, 7, 3, 2, 8, 6]
}


filtered_df = df[df["Experience"] >= 5]

result = filtered_df.groupby("Department")["Salary"].mean()

print(result)


Department
Finance    77500.0
IT         67500.0
Name: Salary, dtype: float64


In [82]:
arr[arr % 2 == 0]


array([14,  0,  0,  6,  0,  0,  0,  0,  6,  0,  2,  2,  0,  0, 34,  0, 36,
       18, 26,  0,  0])

In [84]:
arr[-1, :]  

array([36, 18, 26,  0,  0])

In [85]:
arr[:, -1]


array([19,  0,  2,  0,  0])

In [86]:
arr[-1, :]  
arr[:, -1]

array([19,  0,  2,  0,  0])

In [90]:
arr = np.random.randint(1, 101, (5, 5))

print("Original Array:")
print(arr)

arr[arr > 50] = 0

print("\nUpdated Array (Values > 50 replaced with 0):")
print(arr)


Original Array:
[[ 8 59 95 55 17]
 [67  8 22 86 56]
 [24 24 92 19 33]
 [84 55  9 61 59]
 [ 8 74 81  4 86]]

Updated Array (Values > 50 replaced with 0):
[[ 8  0  0  0 17]
 [ 0  8 22  0  0]
 [24 24  0 19 33]
 [ 0  0  9  0  0]
 [ 8  0  0  4  0]]


In [93]:
A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])
print(A)
print(B)
np.dot(A,B)


[[2 4]
 [6 8]]
[[1 3]
 [5 7]]


array([[22, 34],
       [46, 74]])

In [96]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([30, 40, 70, 80, 90])
np.intersect1d(arr1, arr2)

array([30, 40])

In [97]:
np.setdiff1d(arr1, arr2)

array([10, 20, 50, 60])

In [101]:
df = pd.DataFrame({
    "Player": ["A", "B", "C", "D"],
    "Score": [200, 450, 300, 150]
})
df["Rank"] = df["Score"].rank(method="dense", ascending=False).astype(int)
df.sort_values(by="Score", ascending=False)

Player  Score  Rank
1      B    450     1
2      C    300     2
0      A    200     3
3      D    150     4

In [106]:
data = {
    "CustomerID": ["C001", "C002", "C003"],
    "PurchaseAmount": [100, 200, 150]
}

df = pd.DataFrame(data)

df.to_csv("big_data.csv", index=False)

print("big_data.csv created successfully!")

big_data.csv created successfully!


In [109]:
df = pd.read_csv("big_data.csv")

print(df.head())

df["CustomerID"] = df["CustomerID"].astype("category")

print(df.dtypes)

print(df.describe())


  CustomerID  PurchaseAmount
0       C001             100
1       C002             200
2       C003             150
CustomerID        category
PurchaseAmount       int64
dtype: object
       PurchaseAmount
count             3.0
mean            150.0
std              50.0
min             100.0
25%             125.0
50%             150.0
75%             175.0
max             200.0
