In [3]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})

In [4]:
df[df["Age"] > 25]

Name  Age  Score
1    Bob   27     90
3  David   32     88

In [8]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
df.groupby("Department")["Salary"].mean()

Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64

In [11]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print(a + b)
print(a * b)
print(a ** b)

[11 22 33 44]
[ 10  40  90 160]
[          1     1048576 -1010140999           0]


In [12]:
matrix = np.eye(5, dtype=int)
print(matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [13]:
arr = np.array([10, 25, 39, 50, 19])
print(np.argmax(arr))

3
